terraform {
  required_version = ">= 1.6.0"

  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "~> 1.45"
    }
  }
}

provider "hcloud" {
  token = var.hcloud_token
}

# --- SSH Key ---

resource "hcloud_ssh_key" "studybuddy" {
  name       = "studybuddy-dev"
  public_key = file(var.ssh_public_key_path)
}

# --- Firewall ---

resource "hcloud_firewall" "studybuddy" {
  name = "studybuddy-dev-fw"

  # Allow SSH
  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "22"
    source_ips = ["0.0.0.0/0", "::/0"]
  }

  # Allow dev HTTP
  rule {
    direction  = "in"
    protocol   = "tcp"
    port       = "8080"
    source_ips = ["0.0.0.0/0", "::/0"]
  }

  # Allow all outbound TCP
  rule {
    direction       = "out"
    protocol        = "tcp"
    port            = "any"
    destination_ips = ["0.0.0.0/0", "::/0"]
  }

  # Allow all outbound UDP
  rule {
    direction       = "out"
    protocol        = "udp"
    port            = "any"
    destination_ips = ["0.0.0.0/0", "::/0"]
  }

  # Allow all outbound ICMP
  rule {
    direction       = "out"
    protocol        = "icmp"
    destination_ips = ["0.0.0.0/0", "::/0"]
  }
}

# --- Server ---
#
# Phase 1: user_data runs provision.sh which:
#   - Writes all NixOS config files to /root/studybuddy-nixos/
#   - Runs nixos-infect → VM reboots into NixOS
#
# Phase 2: null_resource "nixos_rebuild" SSHes in after reboot and:
#   - Copies hardware-configuration.nix into the config dir
#   - Runs nixos-rebuild switch --flake .#studybuddy-dev

resource "hcloud_server" "studybuddy" {
  name        = "studybuddy-dev"
  server_type = var.server_type
  image       = "ubuntu-24.04"
  location    = var.server_location

  ssh_keys = [hcloud_ssh_key.studybuddy.id]

  user_data = templatefile("${path.module}/provision.sh.tftpl", {
    ssh_public_key = trimspace(file(var.ssh_public_key_path))
  })

  firewall_ids = [hcloud_firewall.studybuddy.id]

  labels = {
    project = "studybuddy"
    env     = "dev"
  }
}

# --- Post-Reboot NixOS Rebuild ---
#
# After nixos-infect reboots into NixOS, this resource:
# 1. Waits for SSH to come back (nixos-infect preserves root SSH keys)
# 2. Copies hardware-configuration.nix into our config dir
# 3. Runs nixos-rebuild with our flake
#
# NOTE: security.nix sets PermitRootLogin = "no", but that only takes effect
# AFTER nixos-rebuild succeeds. During this provisioning step, root SSH is
# still available from the nixos-infect-generated config.

resource "null_resource" "nixos_rebuild" {
  depends_on = [hcloud_server.studybuddy]

  triggers = {
    server_id = hcloud_server.studybuddy.id
  }

  connection {
    type        = "ssh"
    user        = "root"
    host        = hcloud_server.studybuddy.ipv4_address
    private_key = file(var.ssh_private_key_path)
    timeout     = "10m"

    # nixos-infect reboots the VM; retry until SSH is back
  }

  # Wait for NixOS to be up (nixos-infect reboots into NixOS)
  provisioner "remote-exec" {
    inline = [
      "echo 'Waiting for NixOS boot...'",
      "while [ ! -f /etc/NIXOS ]; do sleep 5; done",
      "echo 'NixOS is up.'",
    ]
  }

  # Copy hardware-configuration.nix and run nixos-rebuild
  provisioner "remote-exec" {
    inline = [
      "set -euo pipefail",

      # The config files were written by provision.sh before nixos-infect ran
      "CONFIG_DIR=/root/studybuddy-nixos",
      "test -d $CONFIG_DIR || { echo 'ERROR: $CONFIG_DIR not found'; exit 1; }",

      # Copy the hardware config generated by nixos-infect
      "cp /etc/nixos/hardware-configuration.nix $CONFIG_DIR/",
      "echo 'hardware-configuration.nix copied'",

      # Enable flakes for this command
      "export NIX_CONFIG='experimental-features = nix-command flakes'",

      # Build and switch
      "cd $CONFIG_DIR",
      "nixos-rebuild switch --flake .#studybuddy-dev 2>&1 | tail -40",

      "echo '=== NixOS rebuild complete ==='",
    ]
  }
}
