#!/usr/bin/env bash
# deploy.sh — Zero-touch provisioning for a StudyBuddy NixOS VM.
#
# Usage (from your local machine):
#   ./nixos/deploy.sh <server-ip> [ssh-key-path]
#
# What it does:
#   1. Runs nixos-infect on a fresh Hetzner Ubuntu/Debian VM to convert it to NixOS
#   2. Waits for reboot
#   3. Copies this nixos/ config to the VM
#   4. Injects your SSH public key
#   5. Runs nixos-rebuild switch --flake .#studybuddy-dev
#
# Prerequisites:
#   - A fresh Hetzner Cloud VM (Ubuntu 22.04 or Debian 12 recommended)
#   - Root SSH access to the VM (Hetzner default)
#   - Your SSH public key for the 'claude' user

set -euo pipefail

SERVER_IP="${1:?Usage: $0 <server-ip> [ssh-key-path]}"
SSH_KEY_PATH="${2:-$HOME/.ssh/hetzner_studybuddy.pub}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# Validate inputs
[[ -f "$SSH_KEY_PATH" ]] || error "SSH public key not found at: $SSH_KEY_PATH"
SSH_PUB_KEY="$(cat "$SSH_KEY_PATH")"

SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10"

wait_for_ssh() {
  local user="$1" host="$2" max_attempts="${3:-30}"
  info "Waiting for SSH on $host (as $user)..."
  for i in $(seq 1 "$max_attempts"); do
    if ssh $SSH_OPTS "$user@$host" true 2>/dev/null; then
      info "SSH is up."
      return 0
    fi
    echo -n "."
    sleep 10
  done
  error "SSH not available after $((max_attempts * 10))s"
}

# ──────────────────────────────────────────────
# Phase 1: nixos-infect
# ──────────────────────────────────────────────
info "Phase 1: Running nixos-infect on $SERVER_IP"
wait_for_ssh root "$SERVER_IP" 6

ssh $SSH_OPTS "root@$SERVER_IP" bash <<'INFECT_EOF'
  # Skip if already NixOS
  if [[ -f /etc/NIXOS ]]; then
    echo "Already NixOS, skipping infect."
    exit 0
  fi
  curl -fsSL https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect | \
    NIX_CHANNEL=nixos-24.05 bash -x 2>&1 | tail -20
INFECT_EOF

info "Waiting for VM reboot after nixos-infect..."
sleep 30
wait_for_ssh root "$SERVER_IP" 30

# ──────────────────────────────────────────────
# Phase 2: Copy config + rebuild
# ──────────────────────────────────────────────
info "Phase 2: Deploying NixOS configuration"

# Copy hardware-configuration.nix from the VM (generated by nixos-infect)
scp $SSH_OPTS "root@$SERVER_IP:/etc/nixos/hardware-configuration.nix" \
  "$SCRIPT_DIR/hardware-configuration.nix"
info "Retrieved hardware-configuration.nix"

# Inject SSH key into users.nix (using a temporary copy)
TMPDIR="$(mktemp -d)"
cp -r "$SCRIPT_DIR"/* "$TMPDIR/"
# Escape special characters in the key for sed
ESCAPED_KEY="$(echo "$SSH_PUB_KEY" | sed 's/[&/\]/\\&/g')"
sed -i "s|@SSH_AUTHORIZED_KEY@|$ESCAPED_KEY|g" "$TMPDIR/users.nix"

# Copy the full config to the VM
ssh $SSH_OPTS "root@$SERVER_IP" "mkdir -p /etc/nixos/studybuddy"
scp $SSH_OPTS -r "$TMPDIR"/* "root@$SERVER_IP:/etc/nixos/studybuddy/"
# Also copy hardware-configuration.nix into the config dir
scp $SSH_OPTS "$SCRIPT_DIR/hardware-configuration.nix" \
  "root@$SERVER_IP:/etc/nixos/studybuddy/"

rm -rf "$TMPDIR"

info "Configuration copied to /etc/nixos/studybuddy/"

# ──────────────────────────────────────────────
# Phase 3: nixos-rebuild
# ──────────────────────────────────────────────
info "Phase 3: Running nixos-rebuild switch"

ssh $SSH_OPTS "root@$SERVER_IP" bash <<'REBUILD_EOF'
  cd /etc/nixos/studybuddy

  # Enable flakes for this command (in case the current system doesn't have it yet)
  export NIX_CONFIG="experimental-features = nix-command flakes"

  nixos-rebuild switch --flake .#studybuddy-dev 2>&1 | tail -30
REBUILD_EOF

info "NixOS configuration applied."

# ──────────────────────────────────────────────
# Phase 4: Verify
# ──────────────────────────────────────────────
info "Phase 4: Verifying setup"

ssh $SSH_OPTS "claude@$SERVER_IP" bash <<'VERIFY_EOF'
  echo "=== System ==="
  uname -a
  echo ""
  echo "=== Java ==="
  java -version 2>&1
  echo ""
  echo "=== Android SDK ==="
  echo "ANDROID_HOME=$ANDROID_HOME"
  ls "$ANDROID_HOME/platforms/" 2>/dev/null || echo "(checking...)"
  echo ""
  echo "=== Node.js ==="
  node --version
  echo ""
  echo "=== Gradle ==="
  gradle --version 2>&1 | head -3
  echo ""
  echo "=== whisper ==="
  which whisper 2>/dev/null && echo "whisper binary: OK" || echo "whisper: not yet available (hash needs fixing)"
  echo ""
  echo "=== Whisper model ==="
  ls -lh /var/lib/whisper/models/ 2>/dev/null || echo "(model not yet downloaded)"
  echo ""
  echo "=== Claude Code ==="
  which claude 2>/dev/null && claude --version 2>/dev/null || echo "(install pending or PATH not set)"
VERIFY_EOF

echo ""
info "=========================================="
info " StudyBuddy VM is ready!"
info " SSH: ssh claude@$SERVER_IP"
info "=========================================="
info ""
warn "If whisper hash errors occurred, see nixos/README.md for how to fix hashes."
